import React from "react";

const Productdata = [
    { "id": 1, "name": "AeroStream Wireless Mouse", "price": 45.00, "category": "Electronics", "stock": 120, "rating": 4.5, "description": "High-precision ergonomic mouse with silent clicks." },
    { "id": 2, "name": "Lumina RGB Keyboard", "price": 89.99, "category": "Electronics", "stock": 45, "rating": 4.8, "description": "Mechanical keyboard with customizable backlight zones." },
    { "id": 3, "name": "Zenith 4K Monitor", "price": 320.50, "category": "Electronics", "stock": 15, "rating": 4.7, "description": "27-inch Ultra HD display with vibrant color accuracy." },
    { "id": 4, "name": "SonicBlast Bluetooth Speaker", "price": 55.00, "category": "Electronics", "stock": 88, "rating": 4.2, "description": "Water-resistant portable speaker with deep bass." },
    { "id": 5, "name": "Vantage Laptop Stand", "price": 29.99, "category": "Office", "stock": 200, "rating": 4.6, "description": "Aluminum adjustable stand for better neck posture." },
    { "id": 6, "name": "Bistro Electric Kettle", "price": 39.00, "category": "Home", "stock": 34, "rating": 4.4, "description": "Fast-boil stainless steel kettle with auto-shutoff." },
    { "id": 7, "name": "Titan Gym Dumbbells", "price": 110.00, "category": "Fitness", "stock": 12, "rating": 4.9, "description": "Set of 2 adjustable dumbbells for home workouts." },
    { "id": 8, "name": "CloudWalk Running Shoes", "price": 75.00, "category": "Fashion", "stock": 60, "rating": 4.3, "description": "Breathable mesh sneakers with cushioned soles." },
    { "id": 9, "name": "Orbit Smart Watch", "price": 199.00, "category": "Electronics", "stock": 25, "rating": 4.5, "description": "Tracks heart rate, sleep, and GPS movements." },
    { "id": 10, "name": "Velvet Comfort Pillow", "price": 25.50, "category": "Home", "stock": 150, "rating": 4.1, "description": "Memory foam pillow with a cooling gel layer." },
    { "id": 11, "name": "GlowUp Face Serum", "price": 18.00, "category": "Beauty", "stock": 300, "rating": 4.7, "description": "Vitamin C serum for radiant and hydrated skin." },
    { "id": 12, "name": "Summit Backpack 30L", "price": 65.00, "category": "Outdoors", "stock": 42, "rating": 4.6, "description": "Durable hiking backpack with rain cover." },
    { "id": 13, "name": "JavaMaster Coffee Press", "price": 32.00, "category": "Home", "stock": 75, "rating": 4.8, "description": "French press for the perfect morning brew." },
    { "id": 14, "name": "IronCore Yoga Mat", "price": 22.99, "category": "Fitness", "stock": 110, "rating": 4.4, "description": "Non-slip 6mm thick mat for yoga and pilates." },
    { "id": 15, "name": "PureSound Earbuds", "price": 129.00, "category": "Electronics", "stock": 55, "rating": 4.5, "description": "Active noise canceling true wireless earbuds." },
    { "id": 16, "name": "Urban Denim Jacket", "price": 55.00, "category": "Fashion", "stock": 30, "rating": 4.2, "description": "Classic blue denim jacket with a modern fit." },
    { "id": 17, "name": "EcoGreen Bamboo Plate Set", "price": 45.00, "category": "Home", "stock": 90, "rating": 4.6, "description": "Sustainable 4-piece dinnerware set." },
    { "id": 18, "name": "PowerUp 20k Power Bank", "price": 49.99, "category": "Electronics", "stock": 140, "rating": 4.7, "description": "High-capacity portable charger with fast charging." },
    { "id": 19, "name": "Chef's Choice Knife Set", "price": 85.00, "category": "Home", "stock": 20, "rating": 4.9, "description": "Professional grade 5-piece stainless steel knives." },
    { "id": 20, "name": "Flexi-Desk Lamp", "price": 19.50, "category": "Office", "stock": 65, "rating": 4.3, "description": "LED desk lamp with 3 brightness levels." },
    { "id": 21, "name": "Trek-Safe First Aid Kit", "price": 24.00, "category": "Outdoors", "stock": 200, "rating": 4.8, "description": "Compact emergency kit for hikers and travelers." },
    { "id": 22, "name": "PixelPro Web Cam", "price": 69.00, "category": "Electronics", "stock": 50, "rating": 4.4, "description": "1080p HD camera with dual microphones." },
    { "id": 23, "name": "CozyKnit Throw Blanket", "price": 35.00, "category": "Home", "stock": 85, "rating": 4.5, "description": "Soft wool-blend blanket for winter nights." },
    { "id": 24, "name": "SteadyShot Tripod", "price": 42.00, "category": "Electronics", "stock": 40, "rating": 4.1, "description": "Lightweight tripod for phones and DSLR cameras." },
    { "id": 25, "name": "PulseFit Jump Rope", "price": 12.99, "category": "Fitness", "stock": 300, "rating": 4.6, "description": "Adjustable speed rope for cardio training." },
    { "id": 26, "name": "GripMaster Gaming Mousepad", "price": 15.00, "category": "Electronics", "stock": 210, "rating": 4.7, "description": "Extra-large cloth pad with anti-fray edges." },
    { "id": 27, "name": "Retro Vinyl Player", "price": 145.00, "category": "Home", "stock": 18, "rating": 4.8, "description": "Turntable with built-in speakers and Bluetooth." },
    { "id": 28, "name": "HydroCool Water Bottle", "price": 28.00, "category": "Fitness", "stock": 130, "rating": 4.5, "description": "Insulated bottle that keeps drinks cold for 24h." },
    { "id": 29, "name": "LushLavender Candle", "price": 14.50, "category": "Home", "stock": 250, "rating": 4.3, "description": "Scented soy wax candle for relaxation." },
    { "id": 30, "name": "SmartPlug WiFi Socket", "price": 12.00, "category": "Electronics", "stock": 400, "rating": 4.4, "description": "Control your appliances via mobile app." },
    { "id": 31, "name": "Shield-X Screen Protector", "price": 9.99, "category": "Electronics", "stock": 500, "rating": 4.6, "description": "Tempered glass for latest smartphone models." },
    { "id": 32, "name": "BoldMove Gym Bag", "price": 38.00, "category": "Fitness", "stock": 70, "rating": 4.5, "description": "Spacious bag with separate shoe compartment." },
    { "id": 33, "name": "SilkSleep Eye Mask", "price": 15.99, "category": "Beauty", "stock": 180, "rating": 4.7, "description": "100% mulberry silk mask for better sleep." },
    { "id": 34, "name": "Titanium Spork", "price": 8.00, "category": "Outdoors", "stock": 150, "rating": 4.2, "description": "Ultralight camping utensil for travelers." },
    { "id": 35, "name": "FocusFlow White Noise Machine", "price": 45.00, "category": "Home", "stock": 60, "rating": 4.4, "description": "Soothing sounds to help sleep and concentration." },
    { "id": 36, "name": "EverLast Leather Belt", "price": 32.00, "category": "Fashion", "stock": 100, "rating": 4.8, "description": "Full-grain leather belt with silver buckle." },
    { "id": 37, "name": "QuickDry Towel Set", "price": 26.00, "category": "Home", "stock": 115, "rating": 4.5, "description": "Microfiber towels perfect for travel and gym." },
    { "id": 38, "name": "NanoDrive 128GB Flash Drive", "price": 19.99, "category": "Electronics", "stock": 300, "rating": 4.3, "description": "Compact USB 3.0 drive for fast data transfer." },
    { "id": 39, "name": "Aura Humidifier", "price": 48.00, "category": "Home", "stock": 45, "rating": 4.6, "description": "Cool mist humidifier with essential oil tray." },
    { "id": 40, "name": "GripFit Resistance Bands", "price": 16.50, "category": "Fitness", "stock": 220, "rating": 4.7, "description": "Set of 5 levels for strength training." },
    { "id": 41, "name": "ClearView Binoculars", "price": 88.00, "category": "Outdoors", "stock": 25, "rating": 4.4, "description": "8x42 magnification for bird watching." },
    { "id": 42, "name": "StylePoint Polo Shirt", "price": 24.00, "category": "Fashion", "stock": 140, "rating": 4.1, "description": "Cotton blend polo with a slim fit design." },
    { "id": 43, "name": "SafeKey Padlock", "price": 18.00, "category": "Home", "stock": 95, "rating": 4.2, "description": "Heavy-duty steel lock with weather resistance." },
    { "id": 44, "name": "Mistify Spray Bottle", "price": 7.50, "category": "Home", "stock": 400, "rating": 4.5, "description": "Continuous fine mist spray for plants or hair." },
    { "id": 45, "name": "LogiType Keyboard Case", "price": 79.00, "category": "Electronics", "stock": 35, "rating": 4.6, "description": "Protective case with integrated keyboard for tablets." },
    { "id": 46, "name": "PeakPerformance Protein Shaker", "price": 14.00, "category": "Fitness", "stock": 180, "rating": 4.4, "description": "BPA-free shaker with whisk ball." },
    { "id": 47, "name": "VividHue Watercolor Set", "price": 35.00, "category": "Art", "stock": 55, "rating": 4.8, "description": "24 vibrant colors with professional brushes." },
    { "id": 48, "name": "SteadyHand Stylus", "price": 22.00, "category": "Electronics", "stock": 120, "rating": 4.3, "description": "Precision pen for touch screens and drawing." },
    { "id": 49, "name": "AirClean Desktop Purifier", "price": 95.00, "category": "Home", "stock": 22, "rating": 4.7, "description": "HEPA filter purifier for small rooms." },
    { "id": 50, "name": "CozyStep Slippers", "price": 19.99, "category": "Fashion", "stock": 160, "rating": 4.2, "description": "Fleece-lined slippers with rubber soles." },
    { "id": 51, "name": "PowerCord 6ft Cable", "price": 12.00, "category": "Electronics", "stock": 500, "rating": 4.5, "description": "Braided USB-C to USB-C fast charging cable." },
    { "id": 52, "name": "OpticClear Lens Cleaner", "price": 6.99, "category": "Beauty", "stock": 350, "rating": 4.6, "description": "Anti-fog spray for glasses and camera lenses." },
    { "id": 53, "name": "TrailMaster Compass", "price": 15.00, "category": "Outdoors", "stock": 80, "rating": 4.4, "description": "High-accuracy navigation tool for hiking." },
    { "id": 54, "name": "BrewReady Coffee Beans", "price": 21.00, "category": "Home", "stock": 110, "rating": 4.9, "description": "1lb medium roast organic arabica beans." },
    { "id": 55, "name": "EcoBag Canvas Tote", "price": 10.00, "category": "Fashion", "stock": 400, "rating": 4.3, "description": "Reusable heavy-duty cotton tote bag." },
    { "id": 56, "name": "SoundGate Wall Mount", "price": 28.00, "category": "Electronics", "stock": 60, "rating": 4.5, "description": "Universal soundbar mount for home theaters." },
    { "id": 57, "name": "FreshMelt Wax Warmer", "price": 22.50, "category": "Home", "stock": 45, "rating": 4.2, "description": "Electric heater for fragrant wax melts." },
    { "id": 58, "name": "SwiftCut Scissors", "price": 9.00, "category": "Office", "stock": 200, "rating": 4.6, "description": "Precision stainless steel craft scissors." },
    { "id": 59, "name": "RuggedPhone Case", "price": 25.00, "category": "Electronics", "stock": 150, "rating": 4.7, "description": "Military-grade drop protection case." },
    { "id": 60, "name": "NightLight Plug-in", "price": 11.00, "category": "Home", "stock": 300, "rating": 4.4, "description": "LED sensor light for hallways and kids' rooms." },
    { "id": 61, "name": "GripTape Tennis Overgrip", "price": 12.00, "category": "Fitness", "stock": 180, "rating": 4.5, "description": "Pack of 3 absorbent non-slip grips." },
    { "id": 62, "name": "SlateGrey Notebook", "price": 16.00, "category": "Office", "stock": 220, "rating": 4.8, "description": "Hardcover dotted journal for bulleting." },
    { "id": 63, "name": "ClearCoat Nail Polish", "price": 8.50, "category": "Beauty", "stock": 250, "rating": 4.1, "description": "Fast-drying high-shine top coat." },
    { "id": 64, "name": "SnapDry Dish Rack", "price": 34.00, "category": "Home", "stock": 40, "rating": 4.5, "description": "Collapsible space-saving drying rack." },
    { "id": 65, "name": "BioFoam Roller", "price": 24.00, "category": "Fitness", "stock": 90, "rating": 4.6, "description": "High-density foam for muscle recovery." },
    { "id": 66, "name": "Digital Food Scale", "price": 19.00, "category": "Home", "stock": 130, "rating": 4.7, "description": "Accurate scale with tare function for cooking." },
    { "id": 67, "name": "AeroFan Desk Fan", "price": 27.00, "category": "Office", "stock": 75, "rating": 4.3, "description": "USB-powered quiet cooling fan." },
    { "id": 68, "name": "EverGlow Lantern", "price": 32.00, "category": "Outdoors", "stock": 50, "rating": 4.8, "description": "Solar-powered LED camping lantern." },
    { "id": 69, "name": "TrueFlex Phone Stand", "price": 14.00, "category": "Electronics", "stock": 210, "rating": 4.4, "description": "Flexible gooseneck holder for desk or bed." },
    { "id": 70, "name": "Linen Napkin Set", "price": 22.00, "category": "Home", "stock": 100, "rating": 4.5, "description": "Set of 6 premium linen table napkins." },
    { "id": 71, "name": "QuickFix Screwdriver Set", "price": 18.50, "category": "Office", "stock": 140, "rating": 4.6, "description": "Small precision kit for electronics repair." },
    { "id": 72, "name": "SunShield Sunscreen", "price": 14.99, "category": "Beauty", "stock": 200, "rating": 4.7, "description": "SPF 50 mineral sunscreen for face." },
    { "id": 73, "name": "GripPro Golf Glove", "price": 16.00, "category": "Fitness", "stock": 110, "rating": 4.2, "description": "Breathable leather glove for left-handed golfers." },
    { "id": 74, "name": "UrbanBeanie Hat", "price": 18.00, "category": "Fashion", "stock": 150, "rating": 4.4, "description": "Soft acrylic knit beanie for winter." },
    { "id": 75, "name": "AquaPure Filter Pitcher", "price": 29.00, "category": "Home", "stock": 65, "rating": 4.6, "description": "Removes chlorine and impurities from tap water." },
    { "id": 76, "name": "SoftTouch Mousepad", "price": 12.00, "category": "Electronics", "stock": 300, "rating": 4.1, "description": "Gel-filled wrist rest for comfort." },
    { "id": 77, "name": "VibeEar Wired Buds", "price": 15.00, "category": "Electronics", "stock": 400, "rating": 4.0, "description": "Classic in-ear headphones with microphone." },
    { "id": 78, "name": "Chef's Apron", "price": 24.50, "category": "Home", "stock": 85, "rating": 4.5, "description": "Heavy-duty canvas apron with pockets." },
    { "id": 79, "name": "MiniProjector Pro", "price": 125.00, "category": "Electronics", "stock": 15, "rating": 4.3, "description": "Portable cinema projector with HDMI input." },
    { "id": 80, "name": "EcoMat TPE Yoga Mat", "price": 38.00, "category": "Fitness", "stock": 50, "rating": 4.8, "description": "Dual-layer eco-friendly yoga mat." },
    { "id": 81, "name": "DeskOrganizer Tray", "price": 21.00, "category": "Office", "stock": 120, "rating": 4.6, "description": "Mesh steel tray for files and stationery." },
    { "id": 82, "name": "SmartBulb Color", "price": 15.99, "category": "Electronics", "stock": 250, "rating": 4.5, "description": "App-controlled LED bulb with 16M colors." },
    { "id": 83, "name": "Pebble Wireless Mouse", "price": 29.00, "category": "Electronics", "stock": 95, "rating": 4.7, "description": "Slim, silent, and modern design." },
    { "id": 84, "name": "HydroFlask 21oz", "price": 34.00, "category": "Outdoors", "stock": 110, "rating": 4.9, "description": "Vacuum insulated standard mouth bottle." },
    { "id": 85, "name": "CoreStrength Ab Roller", "price": 19.99, "category": "Fitness", "stock": 140, "rating": 4.4, "description": "Sturdy wheel for core muscle building." },
    { "id": 86, "name": "SilkScarf Print", "price": 45.00, "category": "Fashion", "stock": 40, "rating": 4.8, "description": "Hand-painted 100% silk neck scarf." },
    { "id": 87, "name": "CleanWave Sonic Toothbrush", "price": 65.00, "category": "Beauty", "stock": 55, "rating": 4.7, "description": "Rechargeable brush with 5 cleaning modes." },
    { "id": 88, "name": "RusticWall Clock", "price": 32.00, "category": "Home", "stock": 30, "rating": 4.3, "description": "12-inch wooden clock with silent movement." },
    { "id": 89, "name": "SafeStep Bath Mat", "price": 18.00, "category": "Home", "stock": 150, "rating": 4.5, "description": "Non-slip absorbent bathroom rug." },
    { "id": 90, "name": "ChargePad Wireless", "price": 22.00, "category": "Electronics", "stock": 200, "rating": 4.4, "description": "Qi-certified 15W fast wireless charger." },
    { "id": 91, "name": "FlexiWorkout Pants", "price": 42.00, "category": "Fitness", "stock": 80, "rating": 4.6, "description": "High-waist moisture-wicking leggings." },
    { "id": 92, "name": "NanoClean Cloths", "price": 12.50, "category": "Home", "stock": 300, "rating": 4.7, "description": "Pack of 12 lint-free microfiber cloths." },
    { "id": 93, "name": "BrewMist Tea Infuser", "price": 9.99, "category": "Home", "stock": 180, "rating": 4.3, "description": "Silicone and stainless steel leaf infuser." },
    { "id": 94, "name": "Traveler's Neck Pillow", "price": 25.00, "category": "Outdoors", "stock": 100, "rating": 4.4, "description": "Contoured memory foam pillow for flights." },
    { "id": 95, "name": "KeyFinder Bluetooth Tag", "price": 19.00, "category": "Electronics", "stock": 250, "rating": 4.2, "description": "Smart tracker to find keys and wallets." },
    { "id": 96, "name": "Gourmet Salt Set", "price": 28.00, "category": "Home", "stock": 60, "rating": 4.8, "description": "Collection of 4 artisanal finishing salts." },
    { "id": 97, "name": "ClipOn Reading Light", "price": 14.00, "category": "Home", "stock": 130, "rating": 4.5, "description": "Rechargeable light for book lovers." },
    { "id": 98, "name": "PureMist Air Freshener", "price": 15.00, "category": "Home", "stock": 200, "rating": 4.1, "description": "Automatic spray with citrus scent." },
    { "id": 99, "name": "FocusTimer Cube", "price": 18.00, "category": "Office", "stock": 85, "rating": 4.6, "description": "Gravity-sensing productivity timer." },
    { "id": 100, "name": "ZenGarden Desk Kit", "price": 24.99, "category": "Office", "stock": 45, "rating": 4.7, "description": "Miniature sand garden for stress relief." },
    { "id": 101, "name": "Luna Pet Bed", "price": 45.00, "category": "Pets", "stock": 55, "rating": 4.8, "description": "Orthopedic memory foam bed for small to medium dogs." },
    { "id": 102, "name": "AutoGlow Car Wax", "price": 22.99, "category": "Automotive", "stock": 130, "rating": 4.5, "description": "Premium carnauba wax for a mirror-like shine." },
    { "id": 103, "name": "ProGrip Gaming Controller", "price": 59.99, "category": "Gaming", "stock": 40, "rating": 4.7, "description": "Wireless controller with haptic feedback and custom triggers." },
    { "id": 104, "name": "EcoSprout Herb Kit", "price": 18.50, "category": "Garden", "stock": 90, "rating": 4.3, "description": "Indoor window kit for growing basil, mint, and parsley." },
    { "id": 105, "name": "Driftwood Table Lamp", "price": 75.00, "category": "Home", "stock": 12, "rating": 4.6, "description": "Handcrafted base made from real coastal driftwood." },
    { "id": 106, "name": "SkyBound Drone X4", "price": 299.00, "category": "Electronics", "stock": 8, "rating": 4.4, "description": "4K camera drone with GPS auto-return and 30min flight time." },
    { "id": 107, "name": "VelvetMatte Lipstick", "price": 14.00, "category": "Beauty", "stock": 210, "rating": 4.2, "description": "Long-lasting smudge-proof lipstick in Ruby Red." },
    { "id": 108, "name": "Titanium Multi-Tool", "price": 38.00, "category": "Outdoors", "stock": 65, "rating": 4.9, "description": "15-in-1 pocket tool including pliers, saw, and bottle opener." },
    { "id": 109, "name": "Bamboo Dish Rack", "price": 26.00, "category": "Home", "stock": 100, "rating": 4.5, "description": "Collapsible, eco-friendly drying rack for kitchenware." },
    { "id": 110, "name": "SonicPulse Electric Flosser", "price": 49.00, "category": "Beauty", "stock": 35, "rating": 4.6, "description": "Water pulse technology for deep gum cleaning." },
    { "id": 111, "name": "Vintage Map Poster", "price": 12.00, "category": "Art", "stock": 150, "rating": 4.7, "description": "Large 24x36 inch aesthetic world map print." },
    { "id": 112, "name": "Kevlar Bike Lock", "price": 55.00, "category": "Fitness", "stock": 45, "rating": 4.8, "description": "Heavy-duty chain lock with anti-pick technology." },
    { "id": 113, "name": "PureBrew Tea Kettle", "price": 42.00, "category": "Home", "stock": 70, "rating": 4.4, "description": "Borosilicate glass kettle with removable tea infuser." },
    { "id": 114, "name": "CloudNine Yoga Block", "price": 11.50, "category": "Fitness", "stock": 200, "rating": 4.5, "description": "High-density EVA foam for yoga support." },
    { "id": 115, "name": "SwiftCharge Car Adapter", "price": 15.99, "category": "Automotive", "stock": 300, "rating": 4.3, "description": "Dual USB-C fast charger for vehicle 12V outlets." },
    { "id": 116, "name": "GlowKey Backlit Mousepad", "price": 24.00, "category": "Gaming", "stock": 85, "rating": 4.6, "description": "Extended desk mat with RGB lighting edges." },
    { "id": 117, "name": "UrbanLeather Wallet", "price": 32.00, "category": "Fashion", "stock": 120, "rating": 4.7, "description": "Slim bifold wallet with RFID blocking technology." },
    { "id": 118, "name": "HydroMist Humidifier", "price": 39.99, "category": "Home", "stock": 50, "rating": 4.5, "description": "Quiet ultrasonic humidifier for bedroom use." },
    { "id": 119, "name": "PeakPioneer Trekking Poles", "price": 68.00, "category": "Outdoors", "stock": 30, "rating": 4.8, "description": "Carbon fiber collapsible poles with cork grips." },
    { "id": 120, "name": "SolarPower Power Bank", "price": 45.00, "category": "Electronics", "stock": 110, "rating": 4.4, "description": "20,000mAh battery with built-in solar panels." },
    { "id": 121, "name": "IronClad Skillet", "price": 34.00, "category": "Home", "stock": 80, "rating": 4.9, "description": "Pre-seasoned 12-inch cast iron frying pan." },
    { "id": 122, "name": "Aura Essential Oils", "price": 21.00, "category": "Beauty", "stock": 140, "rating": 4.7, "description": "Set of 6 organic oils: Lavender, Peppermint, Eucalyptus." },
    { "id": 123, "name": "TidalWave Surfboard Fins", "price": 85.00, "category": "Outdoors", "stock": 20, "rating": 4.6, "description": "High-performance carbon fiber fin set." },
    { "id": 124, "name": "SmartTrack Fitness Ring", "price": 199.00, "category": "Electronics", "stock": 15, "rating": 4.2, "description": "Discreet wearable that tracks steps and heart rate." },
    { "id": 125, "name": "SoftSoothe Eye Drops", "price": 9.50, "category": "Beauty", "stock": 400, "rating": 4.5, "description": "Lubricating drops for dry and tired eyes." },
    { "id": 126, "name": "Rustic Wood Shelves", "price": 48.00, "category": "Home", "stock": 40, "rating": 4.4, "description": "Set of 3 floating shelves for wall decor." },
    { "id": 127, "name": "GripLite Running Socks", "price": 14.00, "category": "Fashion", "stock": 250, "rating": 4.8, "description": "Anti-blister cushioned socks for long distance." },
    { "id": 128, "name": "Digital Meat Thermometer", "price": 16.00, "category": "Home", "stock": 180, "rating": 4.7, "description": "Instant-read probe for perfect grilling." },
    { "id": 129, "name": "NeoGrip Phone Ring", "price": 7.99, "category": "Electronics", "stock": 500, "rating": 4.3, "description": "360-degree rotating kickstand and finger grip." },
    { "id": 130, "name": "LuxeCashmere Throw", "price": 120.00, "category": "Home", "stock": 25, "rating": 4.9, "description": "Ultra-soft 100% cashmere blanket." },
    { "id": 131, "name": "AquaFlex Garden Hose", "price": 35.00, "category": "Garden", "stock": 60, "rating": 4.1, "description": "Expandable 50ft hose that never kinks." },
    { "id": 132, "name": "PetSafe Water Fountain", "price": 39.00, "category": "Pets", "stock": 45, "rating": 4.6, "description": "Automatic circulating water bowl for cats." },
    { "id": 133, "name": "DashCam Pro 1080p", "price": 89.00, "category": "Automotive", "stock": 25, "rating": 4.4, "description": "Wide-angle dashboard camera with night vision." },
    { "id": 134, "name": "EverDry Rain Jacket", "price": 55.00, "category": "Fashion", "stock": 70, "rating": 4.5, "description": "Lightweight waterproof windbreaker with hood." },
    { "id": 135, "name": "Titanium Spatula Set", "price": 28.00, "category": "Home", "stock": 110, "rating": 4.7, "description": "Heat-resistant silicone and titanium kitchen tools." },
    { "id": 136, "name": "FlexiTable Bed Desk", "price": 29.50, "category": "Office", "stock": 130, "rating": 4.4, "description": "Portable lap desk for working from the couch." },
    { "id": 137, "name": "BoldBass Headphones", "price": 145.00, "category": "Electronics", "stock": 22, "rating": 4.8, "description": "Over-ear studio headphones with noise isolation." },
    { "id": 138, "name": "GlowStep Stair Lights", "price": 19.99, "category": "Home", "stock": 160, "rating": 4.3, "description": "Motion-activated LED lights for stairs." },
    { "id": 139, "name": "Zenith Binoculars", "price": 75.00, "category": "Outdoors", "stock": 18, "rating": 4.6, "description": "Compact binoculars for hiking and stargazing." },
    { "id": 140, "name": "PureGlow Facial Brush", "price": 25.00, "category": "Beauty", "stock": 85, "rating": 4.5, "description": "Sonic vibration brush for deep pore cleansing." },
    { "id": 141, "name": "HeavyDuty Trash Can", "price": 65.00, "category": "Home", "stock": 30, "rating": 4.7, "description": "50L stainless steel step-on garbage bin." },
    { "id": 142, "name": "SmartScales Body Comp", "price": 42.00, "category": "Fitness", "stock": 95, "rating": 4.6, "description": "Measures BMI, body fat, and muscle mass." },
    { "id": 143, "name": "Bistro Coffee Grinder", "price": 24.00, "category": "Home", "stock": 115, "rating": 4.4, "description": "Electric blade grinder for fresh coffee beans." },
    { "id": 144, "name": "UrbanBeats Earbuds", "price": 59.00, "category": "Electronics", "stock": 60, "rating": 4.2, "description": "Tangle-free wired buds with deep bass." },
    { "id": 145, "name": "CozyCove Cat Tree", "price": 85.00, "category": "Pets", "stock": 15, "rating": 4.9, "description": "Multi-level scratching post with plush condo." },
    { "id": 146, "name": "RapidDry Bath Towels", "price": 32.00, "category": "Home", "stock": 140, "rating": 4.5, "description": "Ultra-absorbent waffle weave towel set." },
    { "id": 147, "name": "FocusMax Desk Pad", "price": 22.00, "category": "Office", "stock": 200, "rating": 4.7, "description": "Vegan leather desk mat for mouse and keyboard." },
    { "id": 148, "name": "TrailGuard First Aid", "price": 18.00, "category": "Outdoors", "stock": 150, "rating": 4.8, "description": "Waterproof emergency kit for outdoor survival." },
    { "id": 149, "name": "GripStar Basketball", "price": 25.00, "category": "Fitness", "stock": 40, "rating": 4.6, "description": "Indoor/Outdoor composite leather basketball." },
    { "id": 150, "name": "SilverLine Toaster", "price": 45.00, "category": "Home", "stock": 55, "rating": 4.3, "description": "2-slice wide slot toaster with defrost mode." },
    { "id": 151, "name": "PeakFlow Air Filter", "price": 12.00, "category": "Automotive", "stock": 100, "rating": 4.4, "description": "High-flow engine air filter for better fuel economy." },
    { "id": 152, "name": "SolarLantern Pro", "price": 29.99, "category": "Outdoors", "stock": 80, "rating": 4.7, "description": "Collapsible solar lantern with USB charging port." },
    { "id": 153, "name": "LuxeLinen Duvet Set", "price": 110.00, "category": "Home", "stock": 20, "rating": 4.9, "description": "Queen size French linen bedding set." },
    { "id": 154, "name": "SwiftCut Beard Trimmer", "price": 38.00, "category": "Beauty", "stock": 90, "rating": 4.5, "description": "Cordless trimmer with 12 length settings." },
    { "id": 155, "name": "PixelView Digital Frame", "price": 89.00, "category": "Electronics", "stock": 35, "rating": 4.6, "description": "10-inch WiFi frame for sharing photos." },
    { "id": 156, "name": "SteadyGrip Bike Mount", "price": 14.50, "category": "Fitness", "stock": 220, "rating": 4.2, "description": "Universal handlebar mount for smartphones." },
    { "id": 157, "name": "GlowWorm Night Light", "price": 12.00, "category": "Kids", "stock": 300, "rating": 4.4, "description": "Soft silicone nursery light for toddlers." },
    { "id": 158, "name": "TitanBolt Carabiner", "price": 9.00, "category": "Outdoors", "stock": 400, "rating": 4.8, "description": "Heavy-duty climbing grade locking carabiner." },
    { "id": 159, "name": "ChefMaster Mandoline", "price": 35.00, "category": "Home", "stock": 45, "rating": 4.7, "description": "Adjustable vegetable slicer with safety guard." },
    { "id": 160, "name": "OrbitTrack Key Finder", "price": 22.00, "category": "Electronics", "stock": 180, "rating": 4.3, "description": "Bluetooth tracker for keys, wallets, and bags." },
    { "id": 161, "name": "PureBreath Dog Treats", "price": 15.00, "category": "Pets", "stock": 250, "rating": 4.6, "description": "Dental chews for clean teeth and fresh breath." },
    { "id": 162, "name": "AquaShield Phone Pouch", "price": 10.00, "category": "Outdoors", "stock": 350, "rating": 4.5, "description": "Waterproof dry bag for beach and pool." },
    { "id": 163, "name": "RetroGaming Stick", "price": 49.00, "category": "Gaming", "stock": 60, "rating": 4.4, "description": "HDMI stick with 5000+ classic arcade games." },
    { "id": 164, "name": "ComfortGlide Razor", "price": 18.99, "category": "Beauty", "stock": 140, "rating": 4.1, "description": "5-blade razor set with ergonomic handle." },
    { "id": 165, "name": "AeroPost Mailbox", "price": 75.00, "category": "Home", "stock": 12, "rating": 4.7, "description": "Modern wall-mounted locking mailbox." },
    { "id": 166, "name": "SmartFlow Faucet", "price": 125.00, "category": "Home", "stock": 18, "rating": 4.8, "description": "Touchless kitchen faucet with motion sensor." },
    { "id": 167, "name": "PowerLift Belt", "price": 42.00, "category": "Fitness", "stock": 50, "rating": 4.9, "description": "Leather weightlifting belt for back support." },
    { "id": 168, "name": "Silicone Baking Mats", "price": 16.00, "category": "Home", "stock": 210, "rating": 4.7, "description": "Non-stick reusable mats for cookie sheets." },
    { "id": 169, "name": "GripX Gaming Mouse", "price": 32.00, "category": "Gaming", "stock": 95, "rating": 4.5, "description": "Lightweight mouse with 12,000 DPI sensor." },
    { "id": 170, "name": "PureMist Face Spray", "price": 14.00, "category": "Beauty", "stock": 130, "rating": 4.6, "description": "Rosewater facial mist for instant hydration." },
    { "id": 171, "name": "FlexiPole Tent", "price": 145.00, "category": "Outdoors", "stock": 15, "rating": 4.4, "description": "4-person easy setup dome tent for camping." },
    { "id": 172, "name": "DeskMate Cup Holder", "price": 12.00, "category": "Office", "stock": 180, "rating": 4.3, "description": "Clip-on drink holder to prevent desk spills." },
    { "id": 173, "name": "SonicShine Jewelry Cleaner", "price": 39.00, "category": "Home", "stock": 40, "rating": 4.7, "description": "Ultrasonic cleaner for rings, watches, and glasses." },
    { "id": 174, "name": "IronCore Kettlebell", "price": 55.00, "category": "Fitness", "stock": 30, "rating": 4.8, "description": "Solid cast iron kettlebell for strength training." },
    { "id": 175, "name": "EcoWrite Pencil Set", "price": 9.00, "category": "Office", "stock": 500, "rating": 4.5, "description": "Recycled wood pencils with soft lead." },
    { "id": 176, "name": "BoldColor Acrylics", "price": 28.00, "category": "Art", "stock": 75, "rating": 4.9, "description": "12-tube professional grade acrylic paint set." },
    { "id": 177, "name": "UrbanWalk Sandals", "price": 35.00, "category": "Fashion", "stock": 110, "rating": 4.2, "description": "Comfortable leather sandals for summer travel." },
    { "id": 178, "name": "PetBrush Pro", "price": 14.00, "category": "Pets", "stock": 160, "rating": 4.6, "description": "Self-cleaning slicker brush for shedding." },
    { "id": 179, "name": "SmartKey Padlock", "price": 48.00, "category": "Home", "stock": 55, "rating": 4.4, "description": "Fingerprint unlocking lock for gym and gate." },
    { "id": 180, "name": "SteadyView Tablet Stand", "price": 19.99, "category": "Electronics", "stock": 140, "rating": 4.5, "description": "Adjustable aluminum stand for iPad and tablets." },
    { "id": 181, "name": "QuickMix Blender", "price": 65.00, "category": "Home", "stock": 25, "rating": 4.7, "description": "Personal smoothie blender with 2 travel cups." },
    { "id": 182, "name": "AeroFit Yoga Pants", "price": 38.00, "category": "Fitness", "stock": 120, "rating": 4.6, "description": "Seamless leggings with tummy control." },
    { "id": 183, "name": "Lumina Solar Path Lights", "price": 34.00, "category": "Garden", "stock": 90, "rating": 4.3, "description": "Set of 6 waterproof outdoor garden lights." },
    { "id": 184, "name": "SwiftDry Hair Towel", "price": 12.50, "category": "Beauty", "stock": 240, "rating": 4.7, "description": "Microfiber turban for fast hair drying." },
    { "id": 185, "name": "UrbanChic Sunglasses", "price": 25.00, "category": "Fashion", "stock": 100, "rating": 4.4, "description": "Polarized classic wayfarer style shades." },
    { "id": 186, "name": "GripLock Cargo Net", "price": 18.00, "category": "Automotive", "stock": 150, "rating": 4.5, "description": "Elastic net for securing luggage in trunks." },
    { "id": 187, "name": "PeakPioneer Sleeping Bag", "price": 85.00, "category": "Outdoors", "stock": 20, "rating": 4.8, "description": "3-season lightweight sleeping bag for hiking." },
    { "id": 188, "name": "PureSoil Potting Mix", "price": 15.00, "category": "Garden", "stock": 300, "rating": 4.6, "description": "Organic soil blend for indoor plants." },
    { "id": 189, "name": "Digital Sudoku Game", "price": 19.99, "category": "Kids", "stock": 85, "rating": 4.2, "description": "Handheld electronic puzzle game." },
    { "id": 190, "name": "CleanSweep Hand Vac", "price": 42.00, "category": "Home", "stock": 40, "rating": 4.5, "description": "Cordless handheld vacuum for cars and small spills." },
    { "id": 191, "name": "ZenStone Diffuser", "price": 35.00, "category": "Home", "stock": 65, "rating": 4.7, "description": "Ceramic essential oil diffuser with LED light." },
    { "id": 192, "name": "FlexiLight Clip", "price": 9.99, "category": "Office", "stock": 200, "rating": 4.4, "description": "USB rechargeable book light for reading." },
    { "id": 193, "name": "IronPeak Dumbbell Rack", "price": 110.00, "category": "Fitness", "stock": 12, "rating": 4.9, "description": "A-frame steel rack for home gym storage." },
    { "id": 194, "name": "Gourmet Pepper Mill", "price": 24.00, "category": "Home", "stock": 110, "rating": 4.6, "description": "Adjustable ceramic burr grinder for spices." },
    { "id": 195, "name": "SoundWave Vinyl Case", "price": 32.00, "category": "Home", "stock": 45, "rating": 4.8, "description": "Protective storage box for 50+ vinyl records." },
    { "id": 196, "name": "BoldMove Duffle Bag", "price": 45.00, "category": "Fashion", "stock": 70, "rating": 4.5, "description": "Water-resistant travel bag for gym and weekend trips." },
    { "id": 197, "name": "PureGlow Night Cream", "price": 28.00, "category": "Beauty", "stock": 90, "rating": 4.7, "description": "Anti-aging moisturizer with hyaluronic acid." },
    { "id": 198, "name": "SteadyHand Level Tool", "price": 14.00, "category": "Office", "stock": 180, "rating": 4.3, "description": "Magnetic 9-inch torpedo level for DIY." },
    { "id": 199, "name": "EcoFresh Lunch Box", "price": 22.00, "category": "Home", "stock": 140, "rating": 4.6, "description": "Bento-style leakproof stainless steel lunch box." },
    { "id": 200, "name": "FinalFrontier Telescope", "price": 199.00, "category": "Outdoors", "stock": 10, "rating": 4.8, "description": "Beginner telescope with 70mm aperture and tripod." }
]
console.log("data-clicked");

export default Productdata;